if: tag IS present

language: python
dist: xenial
python:
  - '3.7'
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run python setup.py sdist bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: y6EaDXGkQqw402VUhqmMxemWEI1jaKhXdtI7D/go6bH7bHRHt8sdEd+ssEoMUrWzazokaERFDiZk3u+NtbNzA9mF++huv2qEmFT6R9gxEff3kanmZK5ekn+OUo01+lPiaprtI/C2zHJlGuRHmkdJB3e26yYj74C436S0TonIkozD12Sv9IdLU8ZJB3DAhl9TkXzsX97XrGs6tmkHNihT7F0fTBTuKxz+rjf9OWHHl1+UUzcSQeviSkbWyMmcpenS4N1xrhbK1xALcOv/Z8rMu8id7F3US2JhTkjBLefwE2i7qyoGwI6NdAgf44GOATqrmEAeXDvvw9Tt5GlJB6uS1MNm1dpnqFSmnHDUjY7NEZQD/72A4p4vDQ8gGVfXvv7bd9DsGF1vktpobLyjn8MI2GLuNlGtANZ9Z4etraATCcTuZVxLj78QEkltdFYZ+TqCQ5ho1Mz8eZQBFG3rhiWp/vUKFsSQOUWspOCkgbY0gHeqGQQU0R0e7b+nFGhS+3JKweuhF4OmzgQyEtDplBDD5SIM10MRgN8nPgDvkw5NnIlpBRhIJtSNPXjOb1tZO/sANnWD/PSAtKlTHGNAxh2LTq0HV+uUAbmnwjK6BmTYWiWWJEAOsXoIg++zBG+hy6haXST1MiBf4Rh/LO9thiJ03iwtXh166Q/dCE4BYmZKlD8=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
