name: CI

on:
  pull_request:
  push:
    branches:

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Make setuptools_scm able to guess the version.
          # actions/checkout#249
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Ensure pip is up to date
        run: |
          python -m pip install --upgrade pip

      - name: Vendor
        run: |
          python -m pip install invoke
          invoke vendoring.update

      - name: Build
        run: |
          python -m pip install pep517
          python -m pep517.build .

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  test:
    needs: packaging
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9.0-rc.1 - 3.9'
        file-extension:
          - .tar.gz
          - .whl
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Test
        run: |
          python -m pip install *${{ matrix.file-extension }}
          ffffff --version
